Catkin-ProjectName: ecto_openni
Version: 0.3.1
Description: Ecto bindings for the openni sensor.
Author: Ethan Rublee <erublee@willowgarage.com>
Maintainer:  Vincent Rabaud <vrabaud@willowgarage.com>
Homepage:  http://ecto.willowgarage.com

Depends: catkin, boost, ecto, opencv2, openni-dev

Catkin-CopyrightType:  willowgarage
Catkin-DebRulesType: cmake
